/* ──────────────────────────────────────────────────────────
   Tool Registry — single source of truth for every tool.
   To add a tool: 1) add an entry here  2) create the page
   under /src/tools/<slug>/   — that's it.
   ────────────────────────────────────────────────────────── */

import { ToolDefinition } from "./types";

export const tools: ToolDefinition[] = [
  // ─── Image Tools ─────────────────────────────────
  {
    slug: "png-to-jpg",
    name: "PNG to JPG Converter",
    description: "Convert PNG images to JPG format online for free. Reduce file size while maintaining quality.",
    category: "image",
    icon: "image",
    keywords: ["png", "jpg", "jpeg", "convert", "image", "compress", "png to jpg", "convert png to jpg", "image converter", "photo converter", "picture converter", "change png to jpg", "png to jpeg", "free image converter online", "png converter"],
    relatedTools: ["jpg-to-png", "image-resizer"],
  },
  {
    slug: "jpg-to-png",
    name: "JPG to PNG Converter",
    description: "Convert JPG images to PNG format online for free. Preserve transparency and quality.",
    category: "image",
    icon: "image",
    keywords: ["jpg", "jpeg", "png", "convert", "image", "transparency", "jpg to png", "jpeg to png", "convert jpg to png", "image converter", "photo to png", "add transparency", "free jpg to png converter"],
    relatedTools: ["png-to-jpg", "image-resizer"],
  },
  {
    slug: "image-resizer",
    name: "Image Resizer",
    description: "Resize images to any dimension online. Preset sizes for social media, HD, and custom dimensions.",
    category: "image",
    icon: "image",
    keywords: ["resize", "image", "dimension", "scale", "crop", "resize image", "image resizer", "resize photo", "resize picture", "change image size", "reduce image size", "shrink image", "enlarge photo", "photo resizer online", "bulk resize", "social media image size"],
    relatedTools: ["png-to-jpg", "jpg-to-png"],
  },

  // ─── Developer Tools ─────────────────────────────
  {
    slug: "json-formatter",
    name: "JSON Formatter & Validator",
    description: "Format, validate, and beautify JSON data online. Free JSON pretty printer with syntax highlighting.",
    category: "developer",
    icon: "code",
    keywords: ["json", "format", "validate", "beautify", "pretty", "print", "json formatter", "json validator", "json pretty print", "json beautifier", "json viewer", "json lint", "format json online", "json checker", "json parser", "validate json online", "json pretty printer", "minify json"],
    relatedTools: ["json-to-yaml", "yaml-to-json", "xml-formatter", "csv-json-converter"],
    layout: 'full',
  },
  {
    slug: "json-to-yaml",
    name: "JSON to YAML Converter",
    description: "Convert JSON to YAML format instantly. Free online converter with copy support.",
    category: "developer",
    icon: "code",
    keywords: ["json", "yaml", "convert", "json to yaml", "json to yml", "convert json to yaml", "json yaml converter", "json2yaml", "online json to yaml"],
    relatedTools: ["json-formatter", "yaml-to-json"],
    layout: 'full',
  },
  {
    slug: "yaml-to-json",
    name: "YAML to JSON Converter",
    description: "Convert YAML to JSON format instantly. Free online converter with validation.",
    category: "developer",
    icon: "code",
    keywords: ["yaml", "json", "convert", "yaml to json", "yml to json", "convert yaml to json", "yaml json converter", "yaml2json", "parse yaml", "yaml parser online"],
    relatedTools: ["json-formatter", "json-to-yaml"],
    layout: 'full',
  },
  {
    slug: "xml-formatter",
    name: "XML Formatter & Minifier",
    description: "Format, beautify, and minify XML online. Free XML pretty printer and validator.",
    category: "developer",
    icon: "code",
    keywords: ["xml", "format", "beautify", "validate", "minify", "xml formatter", "xml beautifier", "xml validator", "xml minifier", "format xml online", "xml pretty print", "xml viewer", "xml lint", "xml parser"],
    relatedTools: ["json-formatter", "css-minifier"],
    layout: 'full',
  },
  {
    slug: "csv-json-converter",
    name: "CSV ↔ JSON Converter",
    description: "Convert between CSV and JSON formats instantly. Free two-way converter.",
    category: "developer",
    icon: "code",
    keywords: ["csv", "json", "convert", "table", "data", "csv to json", "json to csv", "csv converter", "convert csv to json", "csv json converter", "excel to json", "csv parser", "csv to json online"],
    relatedTools: ["json-formatter", "json-to-yaml"],
    layout: 'full',
  },
  {
    slug: "base64-encoder",
    name: "Base64 Encoder / Decoder",
    description: "Encode and decode Base64 strings online. Free Base64 conversion tool.",
    category: "developer",
    icon: "code",
    keywords: ["base64", "encode", "decode", "convert", "base64 encoder", "base64 decoder", "base64 encode online", "base64 decode online", "encode to base64", "decode base64", "base64 converter", "text to base64", "base64 to text"],
    relatedTools: ["url-encoder", "html-encoder"],
    layout: 'full',
  },
  {
    slug: "url-encoder",
    name: "URL Encoder / Decoder",
    description: "Encode and decode URLs online. Free URL encoding tool for developers.",
    category: "developer",
    icon: "code",
    keywords: ["url", "encode", "decode", "percent", "url encoder", "url decoder", "url encode online", "percent encoding", "encode url", "decode url", "urlencode", "urldecode", "url encoding tool"],
    relatedTools: ["base64-encoder", "html-encoder"],
    layout: 'full',
  },
  {
    slug: "html-encoder",
    name: "HTML Entity Encoder / Decoder",
    description: "Encode and decode HTML entities online. Convert special characters to HTML-safe strings.",
    category: "developer",
    icon: "code",
    keywords: ["html", "entity", "encode", "decode", "special", "characters", "html encoder", "html decoder", "html entities", "html escape", "html unescape", "escape html", "html special characters", "html entity encoder", "encode html online"],
    relatedTools: ["base64-encoder", "url-encoder"],
    layout: 'full',
  },
  {
    slug: "uuid-generator",
    name: "UUID Generator",
    description: "Generate random UUIDs (v4) online. Free bulk UUID generation tool.",
    category: "developer",
    icon: "code",
    keywords: ["uuid", "guid", "generate", "random", "uuid generator", "guid generator", "generate uuid", "uuid v4", "random uuid", "bulk uuid", "uuid online", "unique id generator", "uuid creator"],
    relatedTools: ["password-generator", "hash-generator"],
    layout: 'compact',
  },
  {
    slug: "regex-tester",
    name: "Regex Tester",
    description: "Test regular expressions online with real-time matching and highlighting. Free regex tool.",
    category: "developer",
    icon: "code",
    keywords: ["regex", "regular", "expression", "test", "match", "regex tester", "regex checker", "test regex online", "regular expression tester", "regex debugger", "regex validator", "regex101", "regex playground", "regex match", "regex pattern tester"],
    relatedTools: ["text-diff", "json-formatter"],
  },
  {
    slug: "jwt-decoder",
    name: "JWT Decoder",
    description: "Decode and inspect JSON Web Tokens online. View header, payload and expiration.",
    category: "developer",
    icon: "code",
    keywords: ["jwt", "token", "decode", "json", "web", "auth", "jwt decoder", "jwt debugger", "decode jwt", "jwt viewer", "json web token", "jwt parser", "jwt token decoder", "jwt inspector", "jwt.io"],
    relatedTools: ["base64-encoder", "hash-generator"],
  },
  {
    slug: "hash-generator",
    name: "Hash Generator (SHA-1, SHA-256, SHA-512)",
    description: "Generate SHA-1, SHA-256, and SHA-512 hashes online. Free hash calculator using Web Crypto API.",
    category: "developer",
    icon: "code",
    keywords: ["hash", "sha1", "sha256", "sha512", "checksum", "crypto", "hash generator", "sha256 hash", "sha1 hash", "md5 hash", "hash calculator", "generate hash", "checksum calculator", "file hash", "sha512 generator", "hash online"],
    relatedTools: ["password-generator", "uuid-generator"],
  },
  {
    slug: "timestamp-converter",
    name: "Unix Timestamp Converter",
    description: "Convert Unix timestamps to human-readable dates and vice versa. Live clock included.",
    category: "developer",
    icon: "code",
    keywords: ["timestamp", "unix", "epoch", "date", "convert", "time", "unix timestamp", "epoch converter", "timestamp converter", "unix time", "epoch to date", "date to timestamp", "unix timestamp converter", "current timestamp", "epoch time"],
    relatedTools: ["number-base-converter"],
    layout: 'compact',
  },
  {
    slug: "number-base-converter",
    name: "Number Base Converter",
    description: "Convert between Binary, Octal, Decimal, and Hexadecimal number systems instantly.",
    category: "developer",
    icon: "code",
    keywords: ["binary", "hex", "octal", "decimal", "number", "base", "convert", "number base converter", "binary to decimal", "decimal to binary", "hex to decimal", "decimal to hex", "binary to hex", "hex converter", "binary converter", "octal converter", "base converter"],
    relatedTools: ["timestamp-converter", "hash-generator"],
    layout: 'compact',
  },
  {
    slug: "css-minifier",
    name: "CSS Minifier & Beautifier",
    description: "Minify and beautify CSS online. Reduce file size or make CSS readable again.",
    category: "developer",
    icon: "code",
    keywords: ["css", "minify", "beautify", "compress", "format", "css minifier", "css beautifier", "minify css online", "css compressor", "css formatter", "css pretty print", "format css", "compress css", "beautify css online"],
    relatedTools: ["json-formatter", "xml-formatter"],
    layout: 'full',
  },
  {
    slug: "markdown-to-html",
    name: "Markdown to HTML Converter",
    description: "Convert Markdown to HTML with live preview. Free online Markdown renderer.",
    category: "developer",
    icon: "code",
    keywords: ["markdown", "html", "convert", "render", "preview", "markdown to html", "md to html", "markdown converter", "markdown renderer", "markdown preview", "convert markdown to html", "markdown parser", "markdown viewer online"],
    relatedTools: ["html-encoder", "json-formatter"],
    layout: 'full',
  },
  {
    slug: "color-converter",
    name: "Color Converter (HEX / RGB / HSL)",
    description: "Convert colors between HEX, RGB, and HSL formats. Free color picker and converter.",
    category: "developer",
    icon: "code",
    keywords: ["color", "hex", "rgb", "hsl", "convert", "picker", "color converter", "hex to rgb", "rgb to hex", "hsl to hex", "color picker", "color code", "colour converter", "hex color converter", "color format converter", "css color converter"],
    relatedTools: ["css-minifier"],
    layout: 'compact',
  },

  // ─── Text Tools ──────────────────────────────────
  {
    slug: "word-counter",
    name: "Word Counter",
    description: "Count words, characters, sentences and paragraphs online. Free text analysis tool.",
    category: "text",
    icon: "type",
    keywords: ["word", "count", "character", "sentence", "paragraph", "word counter", "word count", "character count", "count words online", "text counter", "letter counter", "word counter tool", "how many words", "online word counter"],
    relatedTools: ["character-counter", "case-converter"],
  },
  {
    slug: "character-counter",
    name: "Character Counter",
    description: "Count characters with social media platform limits. Twitter, Instagram, LinkedIn and more.",
    category: "text",
    icon: "type",
    keywords: ["character", "count", "twitter", "instagram", "social", "limit", "character counter", "letter counter", "char count", "character count online", "text length", "twitter character limit", "instagram caption length", "sms character count"],
    relatedTools: ["word-counter", "case-converter"],
  },
  {
    slug: "case-converter",
    name: "Case Converter",
    description: "Convert text to uppercase, lowercase, title case, camelCase, snake_case and more.",
    category: "text",
    icon: "type",
    keywords: ["case", "convert", "uppercase", "lowercase", "title", "camel", "snake", "case converter", "text case converter", "change case", "upper case", "lower case", "title case", "camelCase", "snake_case", "UPPERCASE", "PascalCase", "sentence case", "capitalize"],
    relatedTools: ["word-counter", "slug-generator"],
  },
  {
    slug: "slug-generator",
    name: "URL Slug Generator",
    description: "Generate URL-friendly slugs from any text. Free SEO slug tool with live preview.",
    category: "text",
    icon: "type",
    keywords: ["slug", "url", "seo", "generate", "permalink", "slug generator", "url slug", "seo slug", "generate slug", "url friendly", "permalink generator", "slugify", "slug maker", "clean url generator"],
    relatedTools: ["case-converter", "url-encoder"],
    layout: 'compact',
  },
  {
    slug: "lorem-ipsum-generator",
    name: "Lorem Ipsum Generator",
    description: "Generate placeholder Lorem Ipsum text. Free dummy text for designs and prototypes.",
    category: "text",
    icon: "type",
    keywords: ["lorem", "ipsum", "placeholder", "dummy", "text", "lorem ipsum generator", "dummy text", "placeholder text", "filler text", "sample text", "lipsum", "lorem ipsum online", "generate dummy text", "random text generator"],
    relatedTools: ["word-counter", "password-generator"],
  },
  {
    slug: "text-diff",
    name: "Text Diff / Compare",
    description: "Compare two texts side-by-side and see the differences highlighted. Free online diff tool.",
    category: "text",
    icon: "type",
    keywords: ["diff", "compare", "text", "difference", "merge", "text diff", "compare text", "text compare", "diff checker", "find differences", "compare two texts", "online diff", "text comparison tool", "diff tool online"],
    relatedTools: ["word-counter", "line-sorter"],
    layout: 'full',
  },
  {
    slug: "line-sorter",
    name: "Line Sorter & Deduplicator",
    description: "Sort lines alphabetically, by length, remove duplicates, or shuffle. Free text line tool.",
    category: "text",
    icon: "type",
    keywords: ["sort", "lines", "deduplicate", "remove", "duplicates", "shuffle", "line sorter", "sort lines", "sort text", "remove duplicate lines", "alphabetical sort", "sort lines online", "dedup lines", "text line sorter"],
    relatedTools: ["text-diff", "case-converter"],
    layout: 'full',
  },

  // ─── Misc / Utility ──────────────────────────────
  {
    slug: "password-generator",
    name: "Password Generator",
    description: "Generate strong, secure passwords with customizable length and character types. Free and private.",
    category: "misc",
    icon: "misc",
    keywords: ["password", "generate", "secure", "random", "strong", "password generator", "generate password", "random password", "strong password", "secure password generator", "password maker", "password creator", "online password generator"],
    relatedTools: ["uuid-generator", "hash-generator"],
    layout: 'compact',
  },

  // ─── Calculators ─────────────────────────────────
  {
    slug: "percentage-calculator",
    name: "Percentage Calculator",
    description: "Calculate percentages instantly. What is X% of Y, percentage change, increase and decrease.",
    category: "misc",
    icon: "misc",
    keywords: ["percentage", "calculator", "percent", "change", "increase", "decrease", "percentage calculator", "calculate percentage", "what is percent of", "percent change", "percentage increase", "percentage decrease", "percent calculator online", "how to calculate percentage"],
    relatedTools: ["tip-calculator", "bmi-calculator"],
    layout: 'compact',
  },
  {
    slug: "age-calculator",
    name: "Age Calculator",
    description: "Calculate your exact age in years, months and days. Next birthday countdown included.",
    category: "misc",
    icon: "misc",
    keywords: ["age", "calculator", "birthday", "date", "years", "months", "days", "age calculator", "calculate age", "how old am i", "exact age", "age in days", "birthday calculator", "date of birth calculator", "age finder"],
    relatedTools: ["countdown-timer", "timestamp-converter"],
    layout: 'compact',
  },
  {
    slug: "tip-calculator",
    name: "Tip Calculator",
    description: "Calculate tips and split bills easily. Custom tip percentage with per-person breakdown.",
    category: "misc",
    icon: "misc",
    keywords: ["tip", "calculator", "bill", "split", "restaurant", "gratuity", "tip calculator", "calculate tip", "split bill", "bill splitter", "restaurant tip", "how much to tip", "gratuity calculator", "tip calculator online"],
    relatedTools: ["percentage-calculator", "bmi-calculator"],
    layout: 'compact',
  },
  {
    slug: "bmi-calculator",
    name: "BMI Calculator",
    description: "Calculate your Body Mass Index with metric or imperial units. Free BMI health tool.",
    category: "misc",
    icon: "misc",
    keywords: ["bmi", "body", "mass", "index", "calculator", "health", "weight", "bmi calculator", "calculate bmi", "body mass index", "bmi chart", "bmi checker", "am i overweight", "healthy weight calculator", "bmi online"],
    relatedTools: ["percentage-calculator", "age-calculator"],
    layout: 'compact',
  },
  {
    slug: "countdown-timer",
    name: "Countdown Timer",
    description: "Count down to any date and time. Live countdown with days, hours, minutes, seconds.",
    category: "misc",
    icon: "misc",
    keywords: ["countdown", "timer", "date", "event", "clock", "days", "countdown timer", "count down", "days until", "countdown clock", "event countdown", "how many days until", "countdown to date", "online countdown", "timer countdown"],
    relatedTools: ["age-calculator", "timestamp-converter"],
  },
  {
    slug: "random-number-generator",
    name: "Random Number Generator",
    description: "Generate cryptographically random numbers with custom range and count. Free RNG tool.",
    category: "misc",
    icon: "misc",
    keywords: ["random", "number", "generator", "rng", "dice", "range", "random number generator", "random number", "generate random number", "rng online", "random integer", "dice roller", "random number picker", "number randomizer"],
    relatedTools: ["password-generator", "uuid-generator"],
    layout: 'compact',
  },

  // ─── More Text Tools ─────────────────────────────
  {
    slug: "text-repeater",
    name: "Text Repeater",
    description: "Repeat any text multiple times with custom separator. Free text repeat tool.",
    category: "text",
    icon: "type",
    keywords: ["repeat", "text", "duplicate", "copy", "multiply", "text repeater", "repeat text", "text multiplier", "copy paste repeat", "repeat text online", "duplicate text", "text repeat tool"],
    relatedTools: ["word-counter", "lorem-ipsum-generator"],
  },
  {
    slug: "binary-translator",
    name: "Binary Translator",
    description: "Convert text to binary, hexadecimal, or octal and back. Free encoding translator.",
    category: "developer",
    icon: "code",
    keywords: ["binary", "translator", "text", "hex", "octal", "encode", "decode", "binary translator", "text to binary", "binary to text", "binary converter", "binary code translator", "translate binary", "binary text converter"],
    relatedTools: ["base64-encoder", "number-base-converter"],
    layout: 'full',
  },
  {
    slug: "morse-code-translator",
    name: "Morse Code Translator",
    description: "Translate text to Morse code and Morse code to text instantly. Free online translator.",
    category: "text",
    icon: "type",
    keywords: ["morse", "code", "translator", "encode", "decode", "dots", "dashes", "morse code translator", "text to morse code", "morse code to text", "morse code converter", "morse decoder", "translate morse code", "morse code online"],
    relatedTools: ["binary-translator", "case-converter"],
    layout: 'full',
  },

  // ─── More Developer Tools ────────────────────────
  {
    slug: "json-sorter",
    name: "JSON Key Sorter",
    description: "Sort JSON object keys alphabetically (A-Z or Z-A). Deep sorting for nested objects.",
    category: "developer",
    icon: "code",
    keywords: ["json", "sort", "keys", "alphabetical", "order", "organize", "json sorter", "sort json keys", "json key sorter", "alphabetize json", "order json", "json alphabetical", "sort json online"],
    relatedTools: ["json-formatter", "json-to-yaml"],
  },

  // ─── Batch 3: 25 New Tools ──────────────────────

  // Tier 1
  {
    slug: "qr-code-generator",
    name: "QR Code Generator",
    description: "Generate QR codes from any text or URL. Download as SVG or PNG. Free online tool.",
    category: "misc",
    icon: "misc",
    keywords: ["qr", "code", "generator", "barcode", "url", "scan", "qr code generator", "generate qr code", "qr code maker", "create qr code", "qr generator online", "free qr code", "qr code creator", "make qr code"],
    relatedTools: ["base64-encoder", "url-encoder"],
  },
  {
    slug: "image-compressor",
    name: "Image Compressor",
    description: "Compress images online for free. Reduce file size with adjustable quality. JPEG, PNG, WebP.",
    category: "image",
    icon: "image",
    keywords: ["image", "compress", "resize", "reduce", "optimize", "jpeg", "png", "webp", "image compressor", "compress image", "reduce image size", "image optimizer", "compress photo", "shrink image", "compress image online", "photo compressor", "optimize image"],
    relatedTools: ["image-converter", "image-resizer"],
  },
  {
    slug: "unit-converter",
    name: "Unit Converter",
    description: "Convert between units of length, weight, temperature, speed, data, time, and area.",
    category: "misc",
    icon: "misc",
    keywords: ["unit", "converter", "length", "weight", "temperature", "metric", "imperial", "unit converter", "convert units", "measurement converter", "metric to imperial", "cm to inches", "kg to lbs", "celsius to fahrenheit", "miles to km", "feet to meters", "unit conversion calculator"],
    relatedTools: ["px-to-rem-converter", "data-size-converter"],
  },
  {
    slug: "stopwatch",
    name: "Online Stopwatch",
    description: "Free online stopwatch with lap tracking. Accurate to milliseconds. Start, stop, and reset.",
    category: "misc",
    icon: "misc",
    keywords: ["stopwatch", "timer", "lap", "clock", "time", "milliseconds", "online stopwatch", "stopwatch online", "free stopwatch", "lap timer", "split timer", "stopwatch with laps", "digital stopwatch", "web stopwatch"],
    relatedTools: ["countdown-timer", "pomodoro-timer"],
    layout: 'compact',
  },
  {
    slug: "loan-calculator",
    name: "Loan Calculator",
    description: "Calculate monthly payments, total interest, and view full amortization schedule for any loan.",
    category: "misc",
    icon: "misc",
    keywords: ["loan", "calculator", "mortgage", "emi", "interest", "amortization", "payment", "loan calculator", "loan payment calculator", "monthly payment", "emi calculator", "amortization schedule", "interest calculator", "personal loan calculator", "car loan calculator", "calculate loan payment"],
    relatedTools: ["percentage-calculator", "tip-calculator"],
  },
  {
    slug: "color-palette-generator",
    name: "Color Palette Generator",
    description: "Generate beautiful color palettes with harmony rules. Complementary, analogous, triadic, and more.",
    category: "misc",
    icon: "misc",
    keywords: ["color", "palette", "generator", "harmony", "complementary", "analogous", "design", "color palette generator", "colour palette", "generate color palette", "color scheme generator", "color combinations", "color harmony", "color palette maker", "design colors"],
    relatedTools: ["css-gradient-generator", "favicon-generator"],
  },
  {
    slug: "pomodoro-timer",
    name: "Pomodoro Timer",
    description: "Free online Pomodoro timer. 25/5 minute work-break cycles for maximum productivity.",
    category: "misc",
    icon: "misc",
    keywords: ["pomodoro", "timer", "productivity", "focus", "work", "break", "technique", "pomodoro timer", "pomodoro technique", "focus timer", "productivity timer", "25 minute timer", "work timer", "study timer", "pomodoro online", "pomodoro clock"],
    relatedTools: ["stopwatch", "countdown-timer"],
    layout: 'compact',
  },
  {
    slug: "roman-numeral-converter",
    name: "Roman Numeral Converter",
    description: "Convert between Roman numerals and decimal numbers. Includes a reference table.",
    category: "misc",
    icon: "misc",
    keywords: ["roman", "numeral", "converter", "decimal", "number", "I", "V", "X", "L", "C", "D", "M", "roman numeral converter", "roman numerals", "convert roman numerals", "roman to decimal", "decimal to roman", "roman numeral chart", "roman number converter"],
    relatedTools: ["number-base-converter", "binary-translator"],
    layout: 'compact',
  },

  // Tier 2
  {
    slug: "js-beautifier-minifier",
    name: "JS Beautifier & Minifier",
    description: "Beautify or minify JavaScript code online. Format messy JS or compress for production.",
    category: "developer",
    icon: "code",
    keywords: ["javascript", "beautifier", "minifier", "format", "compress", "prettify", "uglify", "js beautifier", "js minifier", "javascript formatter", "format javascript", "beautify js", "minify js", "js formatter online", "javascript prettifier", "compress javascript"],
    relatedTools: ["sql-formatter", "json-formatter"],
    layout: 'full',
  },
  {
    slug: "sql-formatter",
    name: "SQL Formatter",
    description: "Format and beautify SQL queries online. Auto-indent and uppercase keywords.",
    category: "developer",
    icon: "code",
    keywords: ["sql", "formatter", "beautify", "query", "indent", "database", "sql formatter", "format sql", "sql beautifier", "sql pretty print", "format sql query", "sql formatter online", "beautify sql", "sql query formatter", "format sql online"],
    relatedTools: ["js-beautifier-minifier", "json-formatter"],
    layout: 'full',
  },
  {
    slug: "cron-expression-parser",
    name: "Cron Expression Parser",
    description: "Parse and explain cron expressions in plain English. See next 5 run times.",
    category: "developer",
    icon: "code",
    keywords: ["cron", "expression", "parser", "schedule", "job", "linux", "crontab", "cron expression parser", "cron parser", "crontab guru", "cron expression generator", "explain cron", "cron schedule", "cron job", "parse cron expression", "crontab parser"],
    relatedTools: ["timestamp-converter", "regex-tester"],
    layout: 'compact',
  },
  {
    slug: "json-to-typescript",
    name: "JSON to TypeScript",
    description: "Convert JSON objects to TypeScript interfaces instantly. Generate type-safe code.",
    category: "developer",
    icon: "code",
    keywords: ["json", "typescript", "interface", "type", "convert", "generate", "schema", "json to typescript", "json to ts", "generate typescript", "json to interface", "typescript interface generator", "json to type", "convert json to typescript"],
    relatedTools: ["json-formatter", "json-to-yaml"],
    layout: 'full',
  },
  {
    slug: "html-to-markdown",
    name: "HTML to Markdown",
    description: "Convert HTML to clean Markdown. Handles headings, links, lists, bold, italic, and more.",
    category: "developer",
    icon: "code",
    keywords: ["html", "markdown", "convert", "transform", "md", "markup", "html to markdown", "html to md", "convert html to markdown", "html markdown converter", "html2markdown", "html to md converter"],
    relatedTools: ["markdown-preview", "html-entity-encoder"],
    layout: 'full',
  },
  {
    slug: "px-to-rem-converter",
    name: "PX to REM Converter",
    description: "Convert pixels to REM and REM to pixels. With reference table and custom base size.",
    category: "developer",
    icon: "code",
    keywords: ["px", "rem", "converter", "pixel", "css", "font", "size", "responsive", "px to rem", "rem to px", "pixel to rem", "px rem converter", "css px to rem", "convert px to rem", "rem converter", "px to rem calculator"],
    relatedTools: ["unit-converter", "css-gradient-generator"],
    layout: 'compact',
  },
  {
    slug: "json-path-tester",
    name: "JSON Path Tester",
    description: "Test JSONPath expressions against JSON data. See matched values in real-time.",
    category: "developer",
    icon: "code",
    keywords: ["jsonpath", "tester", "query", "json", "path", "selector", "extract", "json path tester", "jsonpath tester", "test jsonpath", "jsonpath expression", "json query", "jsonpath online", "json path finder"],
    relatedTools: ["json-formatter", "json-to-typescript"],
    layout: 'full',
  },

  // Tier 3
  {
    slug: "find-and-replace",
    name: "Find and Replace",
    description: "Find and replace text with regex support, case sensitivity, and whole word matching.",
    category: "text",
    icon: "type",
    keywords: ["find", "replace", "search", "text", "regex", "substitute", "find and replace", "search and replace", "find replace online", "text find replace", "bulk find replace", "regex find replace", "find and replace tool"],
    relatedTools: ["text-diff", "regex-tester"],
    layout: 'full',
  },
  {
    slug: "remove-line-breaks",
    name: "Remove Line Breaks",
    description: "Remove or convert line breaks. Join lines with commas, spaces, or merge into one line.",
    category: "text",
    icon: "type",
    keywords: ["remove", "line", "breaks", "join", "merge", "newline", "remove line breaks", "remove newlines", "join lines", "merge lines", "remove line breaks online", "delete line breaks", "strip newlines", "single line text"],
    relatedTools: ["find-and-replace", "word-counter"],
    layout: 'full',
  },
  {
    slug: "text-to-ascii-art",
    name: "Text to ASCII Art",
    description: "Convert text to ASCII art banner. Generate large text art for READMEs and comments.",
    category: "text",
    icon: "type",
    keywords: ["ascii", "art", "text", "banner", "figlet", "generator", "ascii art generator", "text to ascii", "ascii text", "text art generator", "ascii banner", "figlet online", "ascii art maker", "ascii text generator"],
    relatedTools: ["text-repeater", "morse-code-translator"],
  },
  {
    slug: "emoji-picker",
    name: "Emoji Picker",
    description: "Browse and copy emojis by category. Click any emoji to copy to clipboard instantly.",
    category: "text",
    icon: "type",
    keywords: ["emoji", "picker", "copy", "unicode", "emoticon", "smiley", "emoji picker", "emoji keyboard", "copy emoji", "emoji list", "emoji copy paste", "all emojis", "emoji search", "emoji finder"],
    relatedTools: ["unicode-lookup", "text-repeater"],
  },
  {
    slug: "aspect-ratio-calculator",
    name: "Aspect Ratio Calculator",
    description: "Calculate aspect ratio from width and height. Scale dimensions while maintaining ratio.",
    category: "image",
    icon: "image",
    keywords: ["aspect", "ratio", "calculator", "width", "height", "resize", "scale", "16:9", "aspect ratio calculator", "calculate aspect ratio", "aspect ratio", "screen ratio", "image ratio", "video aspect ratio", "4:3", "21:9", "aspect ratio converter"],
    relatedTools: ["image-resizer", "image-compressor"],
    layout: 'compact',
  },
  {
    slug: "meta-tag-generator",
    name: "Meta Tag Generator",
    description: "Generate HTML meta tags for SEO. Title, description, Open Graph, Twitter Cards, and more.",
    category: "seo",
    icon: "code",
    keywords: ["meta", "tag", "generator", "seo", "html", "open graph", "twitter", "meta tag generator", "seo meta tags", "html meta tags", "og tags", "twitter card", "meta tags for seo", "generate meta tags", "meta description generator"],
    relatedTools: ["open-graph-preview", "robots-txt-generator"],
    layout: 'full',
  },
  {
    slug: "open-graph-preview",
    name: "Open Graph Preview",
    description: "Preview how your page looks when shared on Facebook, Twitter/X, and LinkedIn.",
    category: "seo",
    icon: "code",
    keywords: ["open graph", "og", "preview", "social", "facebook", "twitter", "linkedin", "share", "open graph preview", "og preview", "social media preview", "facebook preview", "twitter card preview", "link preview", "og tag preview", "social share preview"],
    relatedTools: ["meta-tag-generator", "robots-txt-generator"],
    layout: 'full',
  },
  {
    slug: "robots-txt-generator",
    name: "Robots.txt Generator",
    description: "Generate robots.txt files for your website. Control search engine crawling easily.",
    category: "seo",
    icon: "code",
    keywords: ["robots", "txt", "generator", "seo", "crawl", "search engine", "sitemap", "robots.txt generator", "robots txt", "generate robots.txt", "robots.txt creator", "crawl control", "search engine crawl", "robots file generator"],
    relatedTools: ["meta-tag-generator", "open-graph-preview"],
    layout: 'full',
  },
  {
    slug: "favicon-generator",
    name: "Favicon Generator",
    description: "Create custom favicons from text. Choose shape, colors. Download as SVG or PNG.",
    category: "image",
    icon: "image",
    keywords: ["favicon", "generator", "icon", "website", "svg", "png", "logo", "favicon generator", "create favicon", "favicon maker", "website icon", "favicon creator", "generate favicon", "favicon from text", "ico generator"],
    relatedTools: ["image-converter", "color-palette-generator"],
    layout: 'full',
  },
  {
    slug: "data-size-converter",
    name: "Data Size Converter",
    description: "Convert between bits, bytes, KB, MB, GB, TB. SI and binary (IEC) units. Transfer time calculator.",
    category: "developer",
    icon: "code",
    keywords: ["data", "size", "converter", "bytes", "bits", "KB", "MB", "GB", "TB", "binary", "transfer", "data size converter", "byte converter", "kb to mb", "mb to gb", "gb to tb", "data unit converter", "file size converter", "storage converter"],
    relatedTools: ["unit-converter", "number-base-converter"],
    layout: 'compact',
  },

  // ═══════════════════════════════════════════════════
  // 100 Coming-Soon Tools — Planned for future release
  // ═══════════════════════════════════════════════════

  // ─── PDF Tools ───────────────────────────────────
  {
    slug: "pdf-to-word", name: "PDF to Word Converter",
    description: "Convert PDF files to editable Word documents online for free. No signup needed.",
    category: "file-converter", icon: "file",
    keywords: ["pdf", "word", "convert", "docx", "document", "editor", "pdf to word", "pdf converter", "free pdf to docx"],
    comingSoon: true,
  },
  {
    slug: "word-to-pdf", name: "Word to PDF Converter",
    description: "Convert Word documents (DOCX) to PDF format online. Preserve formatting perfectly.",
    category: "file-converter", icon: "file",
    keywords: ["word", "pdf", "convert", "docx", "document", "word to pdf", "doc to pdf"],
    comingSoon: true,
  },
  {
    slug: "pdf-merger", name: "PDF Merger",
    description: "Merge multiple PDF files into one document. Free online PDF combiner.",
    category: "file-converter", icon: "file",
    keywords: ["pdf", "merge", "combine", "join", "pdf merger", "merge pdf files", "combine pdf"],
    comingSoon: true,
  },
  {
    slug: "pdf-splitter", name: "PDF Splitter",
    description: "Split PDF files into separate pages or sections. Extract specific pages from PDF.",
    category: "file-converter", icon: "file",
    keywords: ["pdf", "split", "separate", "extract", "pages", "pdf splitter", "split pdf"],
    comingSoon: true,
  },
  {
    slug: "pdf-compressor", name: "PDF Compressor",
    description: "Compress PDF file size without losing quality. Reduce PDF size online for free.",
    category: "file-converter", icon: "file",
    keywords: ["pdf", "compress", "reduce", "size", "optimize", "compress pdf", "pdf compressor", "shrink pdf"],
    comingSoon: true,
  },
  {
    slug: "image-to-pdf", name: "Image to PDF Converter",
    description: "Convert images (JPG, PNG) to PDF documents. Combine multiple images into one PDF.",
    category: "file-converter", icon: "file",
    keywords: ["image", "pdf", "convert", "jpg to pdf", "png to pdf", "photo to pdf", "picture to pdf"],
    comingSoon: true,
  },
  {
    slug: "pdf-to-image", name: "PDF to Image Converter",
    description: "Convert PDF pages to images (JPG, PNG). Extract images from PDF files.",
    category: "file-converter", icon: "file",
    keywords: ["pdf", "image", "convert", "pdf to jpg", "pdf to png", "extract", "pdf to image"],
    comingSoon: true,
  },
  {
    slug: "excel-to-pdf", name: "Excel to PDF Converter",
    description: "Convert Excel spreadsheets (XLSX) to PDF format online. Free and instant.",
    category: "file-converter", icon: "file",
    keywords: ["excel", "pdf", "convert", "xlsx", "spreadsheet", "excel to pdf", "xls to pdf"],
    comingSoon: true,
  },
  {
    slug: "pdf-to-text", name: "PDF to Text Extractor",
    description: "Extract text content from PDF files. Copy text from any PDF document.",
    category: "file-converter", icon: "file",
    keywords: ["pdf", "text", "extract", "copy", "pdf to text", "pdf text extractor"],
    comingSoon: true,
  },
  {
    slug: "pdf-password-protector", name: "PDF Password Protector",
    description: "Protect PDF files with password encryption. Secure your documents online.",
    category: "file-converter", icon: "file",
    keywords: ["pdf", "password", "protect", "encrypt", "secure", "lock pdf", "pdf security"],
    comingSoon: true,
  },

  // ─── More Image Tools ───────────────────────────
  {
    slug: "image-cropper", name: "Image Cropper",
    description: "Crop images to any size or aspect ratio online. Free image cropping tool.",
    category: "image", icon: "image",
    keywords: ["image", "crop", "cut", "trim", "photo cropper", "crop image online", "picture cropper"],
  },
  {
    slug: "background-remover", name: "Background Remover",
    description: "Remove image backgrounds automatically. Make transparent PNGs in seconds.",
    category: "image", icon: "image",
    keywords: ["background", "remove", "transparent", "png", "cutout", "remove background", "bg remover"],
    comingSoon: true,
  },
  {
    slug: "watermark-generator", name: "Watermark Generator",
    description: "Add text or image watermarks to photos. Protect your images from unauthorized use.",
    category: "image", icon: "image",
    keywords: ["watermark", "add", "text", "image", "protect", "photo watermark", "add watermark"],
    comingSoon: true,
  },
  {
    slug: "image-to-base64", name: "Image to Base64 Encoder",
    description: "Convert images to Base64 encoded strings. Embed images directly in HTML and CSS.",
    category: "image", icon: "image",
    keywords: ["image", "base64", "encode", "data uri", "embed", "image to base64", "convert image"],
  },
  {
    slug: "svg-to-png", name: "SVG to PNG Converter",
    description: "Convert SVG vector graphics to PNG images online. Choose output size and quality.",
    category: "image", icon: "image",
    keywords: ["svg", "png", "convert", "vector", "raster", "svg to png", "svg converter"],
  },
  {
    slug: "webp-to-png", name: "WebP to PNG Converter",
    description: "Convert WebP images to PNG format online for free. Maintain quality and transparency.",
    category: "image", icon: "image",
    keywords: ["webp", "png", "convert", "image", "webp to png", "webp converter"],
  },
  {
    slug: "png-to-webp", name: "PNG to WebP Converter",
    description: "Convert PNG images to WebP for smaller file sizes. Up to 30% smaller than PNG.",
    category: "image", icon: "image",
    keywords: ["png", "webp", "convert", "compress", "smaller", "png to webp", "webp converter"],
  },
  {
    slug: "heic-to-jpg", name: "HEIC to JPG Converter",
    description: "Convert HEIC/HEIF images from iPhone to JPG format. Free online converter.",
    category: "image", icon: "image",
    keywords: ["heic", "jpg", "convert", "iphone", "heif", "apple", "heic to jpg", "heic converter"],
    comingSoon: true,
  },
  {
    slug: "gif-maker", name: "GIF Maker",
    description: "Create animated GIFs from images. Combine multiple frames into one animation.",
    category: "image", icon: "image",
    keywords: ["gif", "maker", "create", "animated", "animation", "gif maker", "make gif", "gif creator"],
    comingSoon: true,
  },
  {
    slug: "image-color-picker", name: "Image Color Picker",
    description: "Pick any color from an image. Get HEX, RGB, and HSL values from photos.",
    category: "image", icon: "image",
    keywords: ["color", "picker", "image", "eyedropper", "hex", "rgb", "pick color from image"],
  },

  // ─── Video & Audio Tools ────────────────────────
  {
    slug: "video-to-gif", name: "Video to GIF Converter",
    description: "Convert video clips to animated GIF images. Extract and create GIFs from any video.",
    category: "file-converter", icon: "file",
    keywords: ["video", "gif", "convert", "animated", "video to gif", "mp4 to gif", "make gif from video"],
    comingSoon: true,
  },
  {
    slug: "video-compressor", name: "Video Compressor",
    description: "Compress video files to reduce size. Maintain quality while shrinking file size.",
    category: "file-converter", icon: "file",
    keywords: ["video", "compress", "reduce", "size", "shrink", "video compressor", "compress video"],
    comingSoon: true,
  },
  {
    slug: "mp3-cutter", name: "MP3 Cutter",
    description: "Cut and trim MP3 audio files online. Create ringtones and audio clips for free.",
    category: "file-converter", icon: "file",
    keywords: ["mp3", "cut", "trim", "audio", "ringtone", "mp3 cutter", "audio cutter", "trim audio"],
    comingSoon: true,
  },
  {
    slug: "audio-converter", name: "Audio Converter",
    description: "Convert audio files between MP3, WAV, OGG, FLAC, and more. Free online converter.",
    category: "file-converter", icon: "file",
    keywords: ["audio", "convert", "mp3", "wav", "ogg", "flac", "audio converter", "mp3 converter"],
    comingSoon: true,
  },
  {
    slug: "video-to-mp4", name: "Video to MP4 Converter",
    description: "Convert video files to MP4 format. Support for AVI, MOV, MKV, WebM and more.",
    category: "file-converter", icon: "file",
    keywords: ["video", "mp4", "convert", "avi", "mov", "mkv", "webm", "video converter", "to mp4"],
    comingSoon: true,
  },

  // ─── More Developer Tools ───────────────────────
  {
    slug: "html-formatter", name: "HTML Formatter & Beautifier",
    description: "Format, beautify, and indent HTML code online. Free HTML pretty printer.",
    category: "developer", icon: "code",
    keywords: ["html", "format", "beautify", "indent", "pretty print", "html formatter", "html beautifier"],
    layout: 'full',
  },
  {
    slug: "typescript-to-javascript", name: "TypeScript to JavaScript",
    description: "Convert TypeScript code to plain JavaScript. Remove types and compile TS to JS.",
    category: "developer", icon: "code",
    keywords: ["typescript", "javascript", "convert", "compile", "ts to js", "remove types", "transpile"],
    comingSoon: true,
  },
  {
    slug: "json-to-graphql", name: "JSON to GraphQL Schema",
    description: "Generate GraphQL schema types from JSON data. Auto-generate types and queries.",
    category: "developer", icon: "code",
    keywords: ["json", "graphql", "schema", "convert", "types", "json to graphql", "graphql generator"],
    layout: 'full',
  },
  {
    slug: "yaml-validator", name: "YAML Validator",
    description: "Validate YAML syntax online. Check for errors and format YAML files.",
    category: "developer", icon: "code",
    keywords: ["yaml", "validate", "syntax", "check", "lint", "yaml validator", "yaml checker"],
  },
  {
    slug: "toml-to-json", name: "TOML to JSON Converter",
    description: "Convert TOML configuration files to JSON format. Free online TOML parser.",
    category: "developer", icon: "code",
    keywords: ["toml", "json", "convert", "config", "toml to json", "toml parser", "toml converter"],
    comingSoon: true,
  },
  {
    slug: "http-status-codes", name: "HTTP Status Codes Reference",
    description: "Complete HTTP status code reference. Search and explore 1xx to 5xx codes with explanations.",
    category: "developer", icon: "code",
    keywords: ["http", "status", "code", "reference", "200", "404", "500", "301", "http codes", "status codes"],
  },
  {
    slug: "css-gradient-generator", name: "CSS Gradient Generator",
    description: "Create beautiful CSS gradients visually. Linear, radial, and conic gradient builder.",
    category: "developer", icon: "code",
    keywords: ["css", "gradient", "generator", "linear", "radial", "background", "css gradient", "gradient maker"],
  },
  {
    slug: "css-flexbox-generator", name: "CSS Flexbox Generator",
    description: "Visual CSS Flexbox layout builder. Generate flexbox code with a drag-and-drop interface.",
    category: "developer", icon: "code",
    keywords: ["css", "flexbox", "generator", "layout", "flex", "css flexbox", "flex generator", "flexbox playground"],
  },
  {
    slug: "css-grid-generator", name: "CSS Grid Generator",
    description: "Visual CSS Grid layout builder. Create complex grid layouts with an interactive tool.",
    category: "developer", icon: "code",
    keywords: ["css", "grid", "generator", "layout", "css grid", "grid generator", "grid layout builder"],
  },
  {
    slug: "tailwind-to-css", name: "Tailwind to CSS Converter",
    description: "Convert Tailwind CSS classes to vanilla CSS. Extract plain CSS from Tailwind utilities.",
    category: "developer", icon: "code",
    keywords: ["tailwind", "css", "convert", "vanilla", "utility", "tailwind to css", "tailwind converter"],
    layout: 'full',
  },
  {
    slug: "svg-optimizer", name: "SVG Optimizer",
    description: "Optimize and minify SVG files. Reduce SVG file size by removing unnecessary metadata.",
    category: "developer", icon: "code",
    keywords: ["svg", "optimize", "minify", "compress", "svg optimizer", "svgo", "reduce svg"],
    layout: 'full',
  },
  {
    slug: "javascript-obfuscator", name: "JavaScript Obfuscator",
    description: "Obfuscate JavaScript code to protect your source. Make JS code unreadable.",
    category: "developer", icon: "code",
    keywords: ["javascript", "obfuscate", "protect", "minify", "encryption", "js obfuscator", "code protection"],
    comingSoon: true,
  },
  {
    slug: "live-html-preview", name: "Live HTML/CSS/JS Preview",
    description: "Write HTML, CSS, and JavaScript with live preview. Free online code playground.",
    category: "developer", icon: "code",
    keywords: ["html", "css", "javascript", "preview", "playground", "codepen", "live preview", "html editor"],
    layout: 'full',
  },
  {
    slug: "code-screenshot", name: "Code Screenshot Generator",
    description: "Create beautiful code screenshots. Customize themes, fonts, and backgrounds.",
    category: "developer", icon: "code",
    keywords: ["code", "screenshot", "image", "carbon", "snippet", "code screenshot", "code to image"],
    comingSoon: true,
  },
  {
    slug: "api-tester", name: "API Tester / REST Client",
    description: "Test REST API endpoints online. Send GET, POST, PUT, DELETE requests and inspect responses.",
    category: "developer", icon: "code",
    keywords: ["api", "tester", "rest", "client", "http", "postman", "api tester", "rest client", "api testing"],
    comingSoon: true,
  },
  {
    slug: "docker-compose-generator", name: "Docker Compose Generator",
    description: "Generate Docker Compose YAML files visually. Build multi-container configurations.",
    category: "developer", icon: "code",
    keywords: ["docker", "compose", "generator", "yaml", "container", "docker compose", "docker generator"],
    comingSoon: true,
  },
  {
    slug: "chmod-calculator", name: "Chmod Calculator",
    description: "Calculate Unix file permissions. Convert between numeric and symbolic chmod notation.",
    category: "developer", icon: "code",
    keywords: ["chmod", "calculator", "permissions", "unix", "linux", "file permissions", "chmod calculator"],
    layout: 'compact',
  },
  {
    slug: "htaccess-generator", name: ".htaccess Generator",
    description: "Generate Apache .htaccess rules. Redirects, caching, security headers, and more.",
    category: "developer", icon: "code",
    keywords: ["htaccess", "generator", "apache", "redirect", "rewrite", "htaccess generator", "htaccess rules"],
  },
  {
    slug: "regex-generator", name: "Regex Generator",
    description: "Generate regular expressions from examples. Describe what you want to match in plain English.",
    category: "developer", icon: "code",
    keywords: ["regex", "generator", "regular expression", "pattern", "regex generator", "regex builder", "regex creator"],
  },
  {
    slug: "git-command-generator", name: "Git Command Generator",
    description: "Find the right Git command for any task. Searchable reference with examples.",
    category: "developer", icon: "code",
    keywords: ["git", "command", "generator", "reference", "cheat sheet", "git commands", "git help"],
    layout: 'compact',
  },

  // ─── More Text & Writing Tools ──────────────────
  {
    slug: "grammar-checker", name: "Grammar Checker",
    description: "Check grammar, spelling, and punctuation errors in your text. Free writing assistant.",
    category: "text", icon: "type",
    keywords: ["grammar", "checker", "spelling", "punctuation", "writing", "grammar checker", "spell check", "proofread"],
    comingSoon: true,
  },
  {
    slug: "paraphrasing-tool", name: "Paraphrasing Tool",
    description: "Rewrite and paraphrase text to avoid plagiarism. Multiple rewriting modes.",
    category: "text", icon: "type",
    keywords: ["paraphrase", "rewrite", "rephrase", "text", "paraphrasing tool", "reword", "synonym"],
    comingSoon: true,
  },
  {
    slug: "text-summarizer", name: "Text Summarizer",
    description: "Summarize long text into key points. Extract important sentences automatically.",
    category: "text", icon: "type",
    keywords: ["summarize", "text", "summary", "condense", "key points", "text summarizer", "tldr"],
    comingSoon: true,
  },
  {
    slug: "plagiarism-checker", name: "Plagiarism Checker",
    description: "Check text for plagiarism. Compare your content against web sources.",
    category: "text", icon: "type",
    keywords: ["plagiarism", "checker", "duplicate", "content", "copy", "plagiarism checker", "plagiarism detector"],
    comingSoon: true,
  },
  {
    slug: "csv-to-table", name: "CSV to HTML Table",
    description: "Convert CSV data to formatted HTML tables. Copy table code instantly.",
    category: "developer", icon: "code",
    keywords: ["csv", "table", "html", "convert", "csv to table", "csv to html", "table generator"],
  },
  {
    slug: "json-to-table", name: "JSON to Table Viewer",
    description: "Convert JSON arrays to readable tables. Visualize JSON data in tabular format.",
    category: "developer", icon: "code",
    keywords: ["json", "table", "viewer", "visualize", "json to table", "json viewer", "json table"],
  },
  {
    slug: "markdown-editor", name: "Markdown Editor",
    description: "Write Markdown with live preview, syntax highlighting, and toolbar shortcuts.",
    category: "developer", icon: "code",
    keywords: ["markdown", "editor", "preview", "write", "markdown editor", "md editor", "markdown writer"],
    layout: 'full',
  },
  {
    slug: "text-to-binary", name: "Text to Binary Converter",
    description: "Convert text to binary code (0s and 1s). Binary to text decoder included.",
    category: "developer", icon: "code",
    keywords: ["text", "binary", "convert", "0", "1", "text to binary", "binary converter"],
    layout: 'full',
  },
  {
    slug: "text-to-hex", name: "Text to Hex Converter",
    description: "Convert text to hexadecimal encoding and back. Free hex encoder/decoder.",
    category: "developer", icon: "code",
    keywords: ["text", "hex", "hexadecimal", "convert", "encode", "text to hex", "hex converter"],
    layout: 'full',
  },
  {
    slug: "unicode-lookup", name: "Unicode Character Lookup",
    description: "Search and browse Unicode characters. Find symbols, emojis, and special characters by name.",
    category: "text", icon: "type",
    keywords: ["unicode", "character", "lookup", "search", "symbol", "unicode lookup", "character map", "special characters"],
  },
  {
    slug: "invisible-character-detector", name: "Invisible Character Detector",
    description: "Detect hidden and invisible characters in text. Find zero-width spaces and control characters.",
    category: "text", icon: "type",
    keywords: ["invisible", "character", "detect", "hidden", "zero-width", "invisible character", "hidden text"],
  },
  {
    slug: "text-encryption", name: "Text Encryption / Decryption",
    description: "Encrypt and decrypt text with AES, DES, and other ciphers. Secure text online.",
    category: "misc", icon: "misc",
    keywords: ["encrypt", "decrypt", "text", "aes", "cipher", "text encryption", "online encryption", "encode"],
    layout: 'full',
  },
  {
    slug: "nato-phonetic-alphabet", name: "NATO Phonetic Alphabet Converter",
    description: "Convert text to NATO phonetic alphabet. Alpha, Bravo, Charlie spelling system.",
    category: "text", icon: "type",
    keywords: ["nato", "phonetic", "alphabet", "alpha", "bravo", "spelling", "nato alphabet", "radio alphabet"],
    layout: 'full',
  },
  {
    slug: "text-to-speech", name: "Text to Speech",
    description: "Convert text to natural-sounding speech. Multiple voices and languages. Download as MP3.",
    category: "text", icon: "type",
    keywords: ["text", "speech", "tts", "voice", "audio", "text to speech", "read aloud", "speak text"],
  },
  {
    slug: "speech-to-text", name: "Speech to Text",
    description: "Transcribe speech to text in real-time. Voice recognition and dictation tool.",
    category: "text", icon: "type",
    keywords: ["speech", "text", "transcribe", "voice", "dictation", "speech to text", "transcription", "voice typing"],
    comingSoon: true,
  },

  // ─── SEO & Marketing Tools ──────────────────────
  {
    slug: "keyword-density-checker", name: "Keyword Density Checker",
    description: "Analyze keyword density in your content. Find most used words and optimize for SEO.",
    category: "seo", icon: "code",
    keywords: ["keyword", "density", "checker", "seo", "analysis", "keyword density", "word frequency", "content analysis"],
  },
  {
    slug: "serp-preview", name: "SERP Preview Tool",
    description: "Preview how your page appears in Google search results. Optimize title and description.",
    category: "seo", icon: "code",
    keywords: ["serp", "preview", "google", "search", "seo", "serp preview", "google preview", "search result preview"],
    layout: 'compact',
  },
  {
    slug: "sitemap-generator", name: "XML Sitemap Generator",
    description: "Generate XML sitemaps for your website. Crawl pages and create sitemaps automatically.",
    category: "seo", icon: "code",
    keywords: ["sitemap", "xml", "generator", "seo", "crawl", "sitemap generator", "xml sitemap", "website sitemap"],
    comingSoon: true,
  },
  {
    slug: "canonical-tag-generator", name: "Canonical Tag Generator",
    description: "Generate canonical URL tags to prevent duplicate content issues.",
    category: "seo", icon: "code",
    keywords: ["canonical", "tag", "url", "seo", "duplicate", "canonical tag", "canonical url", "rel canonical"],
    layout: 'compact',
  },
  {
    slug: "schema-markup-generator", name: "Schema Markup Generator",
    description: "Generate JSON-LD structured data. Schema.org markup for articles, products, FAQs, and more.",
    category: "seo", icon: "code",
    keywords: ["schema", "markup", "json-ld", "structured data", "seo", "schema.org", "rich snippets", "schema generator"],
  },
  {
    slug: "redirect-checker", name: "Redirect Checker",
    description: "Check URL redirect chains and status codes. Trace 301, 302, and meta redirects.",
    category: "seo", icon: "code",
    keywords: ["redirect", "checker", "301", "302", "url", "chain", "redirect checker", "url redirect"],
    comingSoon: true,
  },
  {
    slug: "heading-analyzer", name: "Headline Analyzer",
    description: "Analyze headline quality and emotional impact. Score your blog titles and headings.",
    category: "seo", icon: "code",
    keywords: ["headline", "analyzer", "title", "blog", "score", "headline analyzer", "title analyzer", "blog title"],
  },
  {
    slug: "readability-score", name: "Readability Score Checker",
    description: "Check the readability of your text. Flesch-Kincaid, Gunning Fog, and Coleman-Liau scores.",
    category: "seo", icon: "code",
    keywords: ["readability", "score", "flesch", "gunning fog", "checker", "readability score", "reading level", "text readability"],
  },
  {
    slug: "social-media-post-generator", name: "Social Media Post Generator",
    description: "Generate engaging social media posts. Templates for Twitter, Instagram, LinkedIn, and Facebook.",
    category: "seo", icon: "code",
    keywords: ["social media", "post", "generator", "twitter", "instagram", "linkedin", "facebook", "caption generator"],
    comingSoon: true,
  },
  {
    slug: "hashtag-generator", name: "Hashtag Generator",
    description: "Generate relevant hashtags for your social media posts. Find trending hashtags by topic.",
    category: "seo", icon: "code",
    keywords: ["hashtag", "generator", "instagram", "twitter", "social media", "trending", "hashtag generator"],
    comingSoon: true,
  },

  // ─── Calculator Tools ───────────────────────────
  {
    slug: "compound-interest-calculator", name: "Compound Interest Calculator",
    description: "Calculate compound interest on savings and investments. See growth over time with charts.",
    category: "misc", icon: "misc",
    keywords: ["compound", "interest", "calculator", "savings", "investment", "compound interest calculator", "interest rate"],
    layout: 'compact',
  },
  {
    slug: "salary-calculator", name: "Salary Calculator",
    description: "Convert between hourly, weekly, monthly, and annual salary. Tax estimation included.",
    category: "misc", icon: "misc",
    keywords: ["salary", "calculator", "hourly", "annual", "wage", "salary calculator", "pay calculator", "income"],
    layout: 'compact',
  },
  {
    slug: "tax-calculator", name: "Income Tax Calculator",
    description: "Estimate income tax for US federal tax brackets. Calculate take-home pay after taxes.",
    category: "misc", icon: "misc",
    keywords: ["tax", "calculator", "income", "federal", "bracket", "tax calculator", "income tax", "tax estimator"],
    comingSoon: true,
  },
  {
    slug: "discount-calculator", name: "Discount Calculator",
    description: "Calculate sale prices and savings. Find the final price after percentage or fixed discount.",
    category: "misc", icon: "misc",
    keywords: ["discount", "calculator", "sale", "price", "savings", "percentage off", "discount calculator", "sale price"],
    layout: 'compact',
  },
  {
    slug: "gpa-calculator", name: "GPA Calculator",
    description: "Calculate your Grade Point Average. Support for 4.0 and weighted GPA scales.",
    category: "misc", icon: "misc",
    keywords: ["gpa", "calculator", "grade", "point", "average", "gpa calculator", "college gpa", "cumulative gpa"],
    layout: 'compact',
  },
  {
    slug: "grade-calculator", name: "Grade Calculator",
    description: "Calculate final grades and what you need on the final exam. Weighted grade calculator.",
    category: "misc", icon: "misc",
    keywords: ["grade", "calculator", "final", "exam", "weighted", "grade calculator", "final grade", "what grade do i need"],
    layout: 'compact',
  },
  {
    slug: "fuel-cost-calculator", name: "Fuel Cost Calculator",
    description: "Calculate fuel costs for your trip. Estimate gas expenses based on distance and MPG.",
    category: "misc", icon: "misc",
    keywords: ["fuel", "cost", "calculator", "gas", "trip", "mpg", "fuel calculator", "gas calculator", "trip cost"],
    layout: 'compact',
  },
  {
    slug: "electricity-cost-calculator", name: "Electricity Cost Calculator",
    description: "Calculate electricity costs for your appliances. Estimate monthly and yearly power bills.",
    category: "misc", icon: "misc",
    keywords: ["electricity", "cost", "calculator", "power", "watt", "kwh", "electricity calculator", "power bill"],
    layout: 'compact',
  },
  {
    slug: "calorie-calculator", name: "Calorie Calculator",
    description: "Calculate daily calorie needs based on age, weight, height, and activity level.",
    category: "misc", icon: "misc",
    keywords: ["calorie", "calculator", "tdee", "bmr", "diet", "calorie calculator", "daily calories", "calorie counter"],
    layout: 'compact',
  },
  {
    slug: "date-calculator", name: "Date / Duration Calculator",
    description: "Calculate the difference between two dates. Add or subtract days, months, and years.",
    category: "misc", icon: "misc",
    keywords: ["date", "calculator", "duration", "difference", "days between", "date calculator", "date difference", "how many days"],
    layout: 'compact',
  },
  {
    slug: "mortgage-calculator", name: "Mortgage Calculator",
    description: "Calculate monthly mortgage payments with taxes and insurance. Full amortization schedule.",
    category: "misc", icon: "misc",
    keywords: ["mortgage", "calculator", "home loan", "payment", "interest", "mortgage calculator", "home payment", "house payment"],
    layout: 'compact',
  },
  {
    slug: "investment-calculator", name: "Investment Return Calculator",
    description: "Calculate investment returns with compound growth. Compare investment scenarios.",
    category: "misc", icon: "misc",
    keywords: ["investment", "calculator", "return", "roi", "compound", "investment calculator", "roi calculator", "investment growth"],
    comingSoon: true,
  },
  {
    slug: "currency-converter", name: "Currency Converter",
    description: "Convert between world currencies with live exchange rates. 150+ currencies supported.",
    category: "misc", icon: "misc",
    keywords: ["currency", "converter", "exchange", "rate", "usd", "eur", "currency converter", "money converter", "forex"],
    comingSoon: true,
  },
  {
    slug: "scientific-calculator", name: "Scientific Calculator",
    description: "Full-featured scientific calculator online. Trigonometry, logarithms, factorials, and more.",
    category: "misc", icon: "misc",
    keywords: ["scientific", "calculator", "math", "trigonometry", "logarithm", "scientific calculator", "online calculator", "advanced calculator"],
    comingSoon: true,
  },
  {
    slug: "matrix-calculator", name: "Matrix Calculator",
    description: "Perform matrix operations: addition, multiplication, determinant, inverse, and transpose.",
    category: "misc", icon: "misc",
    keywords: ["matrix", "calculator", "determinant", "inverse", "multiply", "matrix calculator", "linear algebra", "matrix operations"],
    comingSoon: true,
  },

  // ─── Network & Security Tools ───────────────────
  {
    slug: "ip-address-lookup", name: "IP Address Lookup",
    description: "Look up your public IP address and geolocation. Find IP details and ISP information.",
    category: "misc", icon: "misc",
    keywords: ["ip", "address", "lookup", "geolocation", "my ip", "ip lookup", "what is my ip", "ip address finder"],
    comingSoon: true,
  },
  {
    slug: "dns-lookup", name: "DNS Lookup",
    description: "Look up DNS records for any domain. A, AAAA, MX, CNAME, TXT, NS records.",
    category: "developer", icon: "code",
    keywords: ["dns", "lookup", "domain", "records", "mx", "cname", "dns lookup", "dns checker", "nslookup"],
    comingSoon: true,
  },
  {
    slug: "whois-lookup", name: "WHOIS Lookup",
    description: "Look up domain registration details. Find domain owner, registrar, and expiration date.",
    category: "developer", icon: "code",
    keywords: ["whois", "lookup", "domain", "registration", "owner", "whois lookup", "domain lookup", "domain info"],
    comingSoon: true,
  },
  {
    slug: "ssl-checker", name: "SSL Certificate Checker",
    description: "Check SSL/TLS certificate details for any website. Verify expiration and validity.",
    category: "developer", icon: "code",
    keywords: ["ssl", "certificate", "checker", "https", "tls", "ssl checker", "ssl certificate", "ssl test"],
    comingSoon: true,
  },
  {
    slug: "password-strength-checker", name: "Password Strength Checker",
    description: "Check how strong your password is. Get suggestions to improve password security.",
    category: "misc", icon: "misc",
    keywords: ["password", "strength", "checker", "secure", "test", "password strength", "how strong is my password"],
    layout: 'compact',
  },
  {
    slug: "user-agent-parser", name: "User Agent Parser",
    description: "Parse and decode browser user agent strings. Identify browser, OS, and device details.",
    category: "developer", icon: "code",
    keywords: ["user agent", "parser", "browser", "os", "device", "user agent parser", "ua parser", "browser detection"],
    comingSoon: true,
  },
  {
    slug: "http-header-checker", name: "HTTP Header Checker",
    description: "Inspect HTTP response headers for any URL. Check security headers and caching.",
    category: "developer", icon: "code",
    keywords: ["http", "header", "checker", "response", "security", "http headers", "header checker", "response headers"],
    comingSoon: true,
  },
  {
    slug: "port-scanner", name: "Port Scanner",
    description: "Scan open ports on any host. Check if specific ports are open or closed.",
    category: "developer", icon: "code",
    keywords: ["port", "scanner", "open ports", "network", "scan", "port scanner", "port checker", "check open ports"],
    comingSoon: true,
  },

  // ─── Encoding & Conversion Tools ────────────────
  {
    slug: "hex-to-rgb", name: "HEX to RGB Converter",
    description: "Convert HEX color codes to RGB values. Color preview included.",
    category: "developer", icon: "code",
    keywords: ["hex", "rgb", "convert", "color", "hex to rgb", "color converter", "hex color"],
    layout: 'compact',
  },
  {
    slug: "rgb-to-hex", name: "RGB to HEX Converter",
    description: "Convert RGB values to HEX color codes. Find the hex code for any RGB color.",
    category: "developer", icon: "code",
    keywords: ["rgb", "hex", "convert", "color", "rgb to hex", "color converter", "rgb color"],
    layout: 'compact',
  },
  {
    slug: "image-to-text-ocr", name: "Image to Text (OCR)",
    description: "Extract text from images using optical character recognition. Free online OCR tool.",
    category: "image", icon: "image",
    keywords: ["ocr", "image", "text", "extract", "recognize", "image to text", "ocr online", "text recognition"],
    comingSoon: true,
  },
  {
    slug: "barcode-generator", name: "Barcode Generator",
    description: "Generate barcodes in multiple formats. Code 128, EAN-13, UPC-A, and more.",
    category: "misc", icon: "misc",
    keywords: ["barcode", "generator", "code 128", "ean", "upc", "barcode generator", "create barcode", "barcode maker"],
    comingSoon: true,
  },
  {
    slug: "qr-code-scanner", name: "QR Code Scanner",
    description: "Scan QR codes from images or camera. Decode QR code content instantly.",
    category: "misc", icon: "misc",
    keywords: ["qr", "code", "scanner", "reader", "decode", "qr scanner", "scan qr code", "qr code reader"],
    comingSoon: true,
  },
  {
    slug: "epub-to-pdf", name: "EPUB to PDF Converter",
    description: "Convert EPUB ebooks to PDF format. Read your ebooks anywhere.",
    category: "file-converter", icon: "file",
    keywords: ["epub", "pdf", "convert", "ebook", "epub to pdf", "ebook converter", "epub converter"],
    comingSoon: true,
  },
  {
    slug: "json-to-xml", name: "JSON to XML Converter",
    description: "Convert JSON data to XML format. Free online JSON to XML transformer.",
    category: "developer", icon: "code",
    keywords: ["json", "xml", "convert", "transform", "json to xml", "xml converter", "data converter"],
    layout: 'full',
  },
];

/** Lookup a tool by slug. Returns undefined if not found. */
export function getToolBySlug(slug: string): ToolDefinition | undefined {
  return tools.find((t) => t.slug === slug);
}

/** Get all tools in a category */
export function getToolsByCategory(category: string): ToolDefinition[] {
  return tools.filter((t) => t.category === category);
}

/** Get all published (non-coming-soon) tools */
export function getPublishedTools(): ToolDefinition[] {
  return tools.filter((t) => !t.comingSoon);
}

/** Get all tool slugs (for static path generation) */
export function getAllToolSlugs(): string[] {
  return tools.map((t) => t.slug);
}
