/**
 * Compact usage hints shown below the tool description.
 * Each hint is a single actionable sentence so the user knows
 * exactly what to do — no scrolling, no jargon.
 */

const hints: Record<string, string> = {
  // ─── Image Tools ─────────────────────────────────
  "png-to-jpg": "Drop or select PNG images, pick a quality preset, then download individually or Save All.",
  "jpg-to-png": "Drop or select JPG images, then download individually or Save All.",
  "image-resizer": "Drop an image, choose a preset size or enter custom dimensions, then download.",
  "image-compressor": "Drop an image, adjust quality and max width, then download the compressed version.",
  "image-cropper": "Drop an image, set crop area with X/Y/Width/Height, then download the cropped result.",
  "image-to-base64": "Drop an image to get its Base64-encoded data URI — copy it to your clipboard.",
  "image-color-picker": "Drop an image, hover over it to see pixel colors, click to copy the HEX code.",
  "svg-to-png": "Drop an SVG file, pick a scale (1×–4×), then download as PNG.",
  "webp-to-png": "Drop WebP images, then download individually or Save All.",
  "png-to-webp": "Drop PNG or JPG images to convert to WebP, then download individually or Save All.",
  "favicon-generator": "Enter text, pick colors and shape, then download as SVG or PNG.",
  "qr-code-generator": "Type or paste text/URL, customize colors and size, then download the QR code.",
  "color-palette-generator": "Click generate to create palettes, lock colors you like, and copy HEX values.",
  "color-converter": "Enter a color in any format (HEX, RGB, HSL) and see all conversions instantly.",
  "hex-to-rgb": "Enter a HEX color code to see its RGB, HSL, and other representations.",
  "rgb-to-hex": "Enter RGB values to get the HEX code and other color formats.",

  // ─── Developer Tools ─────────────────────────────
  "json-formatter": "Paste JSON in the left panel — see it formatted, validated, and highlighted on the right.",
  "json-to-yaml": "Paste JSON on the left, get YAML output on the right — copy with one click.",
  "yaml-to-json": "Paste YAML on the left, get JSON output on the right — copy with one click.",
  "xml-formatter": "Paste XML to format and indent it. Copy the beautified result.",
  "csv-json-converter": "Paste CSV or JSON on the left, toggle the conversion direction, and copy the output.",
  "base64-encoder": "Paste text to encode or decode Base64 — switch modes with the toggle.",
  "url-encoder": "Paste text or a URL to encode/decode — switch modes with the toggle.",
  "html-encoder": "Paste HTML to encode special characters, or decode encoded HTML back to readable markup.",
  "uuid-generator": "Click Generate to create UUIDs. Adjust quantity and version, then copy.",
  "regex-tester": "Enter a regex pattern and test string — matches highlight in real time.",
  "jwt-decoder": "Paste a JWT token to see its decoded header, payload, and expiration info.",
  "hash-generator": "Enter text, pick an algorithm (MD5, SHA-1, SHA-256, etc.), and copy the hash.",
  "timestamp-converter": "Enter a Unix timestamp or pick a date — see conversions between all formats.",
  "number-base-converter": "Enter a number, select input/output base (binary, octal, decimal, hex), and convert.",
  "css-minifier": "Paste CSS to minify it, or paste minified CSS to beautify it.",
  "markdown-to-html": "Type Markdown on the left, see rendered HTML on the right — copy the output.",
  "json-sorter": "Paste JSON to sort all keys alphabetically — nested objects too.",
  "js-beautifier-minifier": "Paste JavaScript to beautify or minify it — toggle between modes.",
  "sql-formatter": "Paste a SQL query to format it with proper indentation and syntax highlighting.",
  "cron-expression-parser": "Enter a cron expression to see a human-readable description and next run times.",
  "json-to-typescript": "Paste JSON to generate TypeScript interfaces — copy the output.",
  "html-to-markdown": "Paste HTML on the left, get clean Markdown on the right.",
  "px-to-rem-converter": "Enter a pixel value and base font size to get the rem equivalent.",
  "json-path-tester": "Paste JSON and enter a JSONPath expression to query and extract data.",
  "html-formatter": "Paste HTML to format and indent it with proper nesting.",
  "json-to-graphql": "Paste JSON to generate a GraphQL schema with types and queries.",
  "yaml-validator": "Paste YAML to validate its syntax — errors are highlighted instantly.",
  "http-status-codes": "Browse or search HTTP status codes with descriptions and usage examples.",
  "css-gradient-generator": "Pick colors and direction to generate CSS gradient code — copy to clipboard.",
  "css-flexbox-generator": "Configure flexbox properties visually and copy the generated CSS.",
  "css-grid-generator": "Set rows, columns, and gaps visually — copy the generated CSS Grid code.",
  "tailwind-to-css": "Paste Tailwind classes to see the equivalent plain CSS.",
  "svg-optimizer": "Paste SVG markup to optimize and minify it — see the size reduction.",
  "live-html-preview": "Type HTML/CSS/JS on the left, see a live preview on the right.",
  "chmod-calculator": "Toggle permission checkboxes to generate chmod numeric and symbolic notation.",
  "htaccess-generator": "Select rules (redirects, caching, security) and generate .htaccess code.",
  "regex-generator": "Describe what you want to match in plain English, get a regex pattern.",
  "git-command-generator": "Pick a Git operation and fill in the details to get the right command.",
  "json-to-xml": "Paste JSON to convert it to XML format — copy the output.",
  "json-to-table": "Paste a JSON array to render it as a formatted HTML table.",
  "csv-to-table": "Paste CSV data to render it as a formatted, sortable table.",
  "markdown-editor": "Write Markdown with a live preview — export to HTML or copy the source.",

  // ─── Text Tools ──────────────────────────────────
  "word-counter": "Paste or type text — see word count, character count, sentences, and reading time instantly.",
  "character-counter": "Paste or type text to see detailed character, word, and line statistics.",
  "case-converter": "Paste text and click a case button: UPPER, lower, Title, Sentence, camelCase, etc.",
  "slug-generator": "Type a title or phrase to generate a URL-friendly slug — copy with one click.",
  "lorem-ipsum-generator": "Pick paragraphs, sentences, or words, set a count, and generate placeholder text.",
  "text-diff": "Paste two texts side by side to see the differences highlighted.",
  "line-sorter": "Paste lines of text, choose sort order (A–Z, Z–A, random, reverse), and copy.",
  "find-and-replace": "Paste text, enter a search term and replacement, then apply — supports regex.",
  "remove-line-breaks": "Paste text to remove line breaks, extra spaces, or blank lines.",
  "text-repeater": "Enter text and a repeat count — get the repeated output instantly.",
  "binary-translator": "Enter text to get binary, or paste binary to decode it back to text.",
  "morse-code-translator": "Enter text to get Morse code, or paste Morse to decode it. Play audio too.",
  "text-to-ascii-art": "Type text and pick a font to generate ASCII art — copy or download.",
  "emoji-picker": "Search or browse emojis by category — click to copy any emoji.",
  "text-to-binary": "Enter text to convert to binary, or paste binary to decode back to text.",
  "text-to-hex": "Enter text to convert to hexadecimal, or paste hex to decode back to text.",
  "unicode-lookup": "Search for Unicode characters by name — click to copy the character or code point.",
  "invisible-character-detector": "Paste text to find and highlight hidden/invisible characters.",
  "text-encryption": "Enter text and a password to encrypt — paste encrypted text and password to decrypt.",
  "nato-phonetic-alphabet": "Type text to see its NATO phonetic alphabet spelling.",
  "text-to-speech": "Type or paste text, select a voice, and click Play to hear it spoken aloud.",

  // ─── SEO Tools ───────────────────────────────────
  "meta-tag-generator": "Fill in title, description, and URL to generate meta tags — copy the HTML.",
  "open-graph-preview": "Enter your page details to preview how it looks when shared on social media.",
  "robots-txt-generator": "Configure crawl rules and generate a robots.txt file — copy or download.",
  "keyword-density-checker": "Paste text to see keyword frequency, density percentages, and top phrases.",
  "serp-preview": "Enter title, URL, and description to preview how your page looks in Google results.",
  "canonical-tag-generator": "Enter your page URL to generate the canonical link tag — copy the HTML.",
  "schema-markup-generator": "Pick a schema type, fill in the fields, and copy the JSON-LD markup.",
  "heading-analyzer": "Paste your heading/title to get a score with length, word, and readability analysis.",
  "readability-score": "Paste text to get Flesch, Gunning Fog, and other readability scores.",

  // ─── Calculators & Misc ──────────────────────────
  "password-generator": "Set length, choose character types, and generate secure passwords — copy instantly.",
  "percentage-calculator": "Enter values to calculate percentages, increases, decreases, or differences.",
  "age-calculator": "Enter your birthdate to see your exact age in years, months, and days.",
  "tip-calculator": "Enter bill amount, tip percentage, and number of people to split.",
  "bmi-calculator": "Enter height and weight to calculate your BMI and see your category.",
  "countdown-timer": "Set hours, minutes, and seconds — start the countdown with audio alert.",
  "random-number-generator": "Set min/max range and quantity, then generate random numbers.",
  "stopwatch": "Click Start to begin timing, Lap to record splits, Reset to clear.",
  "loan-calculator": "Enter loan amount, interest rate, and term to see monthly payments and total cost.",
  "pomodoro-timer": "Click Start for a 25-minute focus session with automatic break intervals.",
  "roman-numeral-converter": "Enter a number or Roman numeral to convert between the two formats.",
  "unit-converter": "Select a category (length, weight, temp, etc.), enter a value, and see all conversions.",
  "aspect-ratio-calculator": "Enter width and height to calculate the aspect ratio and scale proportionally.",
  "data-size-converter": "Enter a data size to convert between bytes, KB, MB, GB, TB, and more.",
  "compound-interest-calculator": "Enter principal, rate, time, and compounding frequency to see growth over time.",
  "salary-calculator": "Enter your salary to see hourly, weekly, monthly, and annual breakdowns.",
  "discount-calculator": "Enter original price and discount percentage to see the final price and savings.",
  "gpa-calculator": "Add courses with grades and credit hours to calculate your GPA.",
  "grade-calculator": "Enter assignment scores and weights to calculate your overall grade.",
  "fuel-cost-calculator": "Enter distance, fuel efficiency, and price per gallon/liter to estimate trip cost.",
  "electricity-cost-calculator": "Enter wattage, hours of use, and rate to estimate electricity cost.",
  "calorie-calculator": "Enter age, height, weight, and activity level to estimate daily calorie needs.",
  "date-calculator": "Pick two dates to find the difference, or add/subtract days from a date.",
  "mortgage-calculator": "Enter home price, down payment, rate, and term to see monthly payments.",
  "password-strength-checker": "Type a password to see its strength score, entropy, and estimated crack time.",
};

/**
 * Returns the usage hint for a tool, or a generic fallback.
 */
export function getUsageHint(slug: string): string {
  return hints[slug] ?? "";
}
